name: Nest JS Image Build, Push on Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t mirfanalisolutions/blog-nest:latest \
            -t mirfanalisolutions/blog-nest:${{ github.sha }} \
            -f server/Dockerfile \  # Specify the path to your Dockerfile
            -o type=local,dest=./output \
            ./server  # Specify the path to your server code

          docker push mirfanalisolutions/blog-nest:latest
          docker push mirfanalisolutions/blog-nest:${{ github.sha }}
