name: MEAN Stack Blog Project Images Build, Push on Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-folder:
          - image: 'nest'
            folder: 'server'
          - image: 'angular'
            folder: 'client'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image-folder.folder }}
          file: ./${{ matrix.image-folder.folder }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          target: production
          tags: |
            mirfanalisolutions/blog-${{ matrix.image-folder.image }}:latest
